FROM maven:3.8.4-openjdk-17 as frontend
WORKDIR /app
COPY . /app/.
RUN mvn -f /app/pom.xml clean install -Dmaven.test.skip=true

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=frontend /app/target/*.jar /app/*.jar
ENTRYPOINT ["java", "-jar", "/app/*.jar"]