version: "3"
services:

  mysqldb:
    image: mysql:5.7.34
    container_name: validator_mysqldb_1
    restart: unless-stopped
    environment:
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      
  api: 
    build: api
    env_file: ./.env
    container_name : validator_api_1
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_ROOT_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports: 
      - $SPRING_LOCAL_API_PORT:$SPRING_DOCKER_API_PORT
    volumes:
      - "${HOME}/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      - mysqldb

  ui: 
    build: ui
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_UI_PORT:$SPRING_DOCKER_UI_PORT
    volumes:
      - "${HOME}/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      
  discovery:
    build: discovery
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_DISCOVERY_PORT:$SPRING_DOCKER_DISCOVERY_PORT
    volumes:
      - "${HOME}/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      
  config:
    build: config
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_CONFIG_PORT:$SPRING_DOCKER_CONFIG_PORT
      
  gateway:
    build: gateway
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_GATEWAY_PORT:$SPRING_DOCKER_GATEWAY_PORT
    restart: always
    depends_on:
      - config
      
volumes:
  db: