version: "3"
services:

  backend: 
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_ROOT_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports: 
      - $SPRING_LOCAL_BECKEND_PORT:$SPRING_DOCKER_BECKEND_PORT
    volumes:
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7.34
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  frontend: 
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_FRONTEND_PORT:$SPRING_DOCKER_FRONTEND_PORT
    volumes:
      - "${HOME}/.m2:/root/.m2"
    depends_on: 
      - backend
      
volumes:
  db: