version: "3"
services:

  mysqldb:
    image: mysql:5.7.34
    container_name: validator_mysqldb_1
    restart: unless-stopped
    environment:
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      
  backend: 
    build: backend-ms
    env_file: ./.env
    container_name : validator_backend_1
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_ROOT_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports: 
      - $SPRING_LOCAL_BACKEND_PORT:$SPRING_DOCKER_BACKEND_PORT
    volumes:
      - "$HOME/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      - mysqldb

  frontend: 
    build: frontend-ms
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_FRONTEND_PORT:$SPRING_DOCKER_FRONTEND_PORT
    volumes:
      - "$HOME/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      - backend
      
  discovery:
    build: discovery-is
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_DISCOVERY_PORT:$SPRING_DOCKER_DISCOVERY_PORT
    volumes:
      - "$HOME/.m2:/root/.m2"
    restart: always
    depends_on:
      - config
      
  config:
    build: config-is
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_CONFIG_PORT:$SPRING_DOCKER_CONFIG_PORT
      
volumes:
  db: