spring:
    application:
        name: discovery
            
server:
    port: 8761
    
eureka:
    instance:
        prefer-ip-address: false
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${DISCOVERY_SERVER_HOST:localhost}:8761/eureka/
        server:
            waitTimeInMsWhenSyncEmpty: 0