## YAML Template.
---
logging:
  level:
    org.springframework: ERROR
    com.dev.validator: DEBUG
    org.hibernate.SQL: OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
  
server:
  port:
    8088
    
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  data:
    rest: 
      base-path: /api
  devtools:
    livereload:
      enabled: true 
    restart:
      enabled: true
      additional-paths: /src/main        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: validator
    password: validator
    url: jdbc:mysql://localhost:3306/validator
  jpa:
    properties:
        hibernate:
            show_sql: false
    show-sql : false
    hibernate:
      ddl-auto: update