## YAML Template.
---
logging:
  level:
    org.springframework: ERROR
    com.zaxxer.hikari: TRACE
    com.dev.validator: DEBUG
    org.hibernate.SQL: OFF
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
  
server:
  port: ${SPRING_LOCAL_API_PORT:8088}
    
validator:
  url: https://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_order
    
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  data:
    rest: 
      base-path: /base/api
  devtools:
    livereload:
      enabled: true 
    restart:
      enabled: true
      additional-paths: /src/main        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLDB_ROOT_USER:validator}
    password: ${MYSQLDB_ROOT_PASSWORD:validator}
    url: jdbc:mysql://${MYSQLDB_SERVER_HOST:localhost}:3306/validator
  jpa:
    properties:
        hibernate:
            show_sql: false
            dialect: org.hibernate.dialect.MySQLDialect
    show-sql : false
    hibernate:
      ddl-auto: update
  