## YAML Template.
---
  
server:
  port:
    9090
    
spring:
  application:
    name: frontend
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  data:
    rest: 
      base-path: /api
  devtools:
    livereload:
      enabled: true 
    restart:
      enabled: true
      additional-paths: /src/main        
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: validator
    password: validator
    url: jdbc:mysql://localhost:3306/validator
  jpa:
    properties:
        hibernate:
            show_sql: false
            dialect: org.hibernate.dialect.MySQLDialect
    show-sql : false
    hibernate:
      ddl-auto: update

eureka:
    client:
        service-url:
            defaultZone: http://discovery:8761/eureka/